// countryData.js
export const countryData = [
  {
    name: "Afghanistan",
    code: "AF",
    dialCode: "+93",
    flag: "🇦🇫",
    phoneLength: 9,
  },
  {
    name: "Albania",
    code: "AL",
    dialCode: "+355",
    flag: "🇦🇱",
    phoneLength: 9,
  },
  {
    name: "Algeria",
    code: "DZ",
    dialCode: "+213",
    flag: "🇩🇿",
    phoneLength: 9,
  },
  {
    name: "Andorra",
    code: "AD",
    dialCode: "+376",
    flag: "🇦🇩",
    phoneLength: 9,
  },
  {
    name: "Angola",
    code: "AO",
    dialCode: "+244",
    flag: "🇦🇴",
    phoneLength: 9,
  },
  {
    name: "Argentina",
    code: "AR",
    dialCode: "+54",
    flag: "🇦🇷",
    phoneLength: 10,
  },
  {
    name: "Armenia",
    code: "AM",
    dialCode: "+374",
    flag: "🇦🇲",
    phoneLength: 8,
  },
  {
    name: "Australia",
    code: "AU",
    dialCode: "+61",
    flag: "🇦🇺",
    phoneLength: 9,
  },
  {
    name: "Austria",
    code: "AT",
    dialCode: "+43",
    flag: "🇦🇹",
    phoneLength: 10,
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    dialCode: "+994",
    flag: "🇦🇿",
    phoneLength: 9,
  },
  {
    name: "Bahrain",
    code: "BH",
    dialCode: "+973",
    flag: "🇧🇭",
    phoneLength: 8,
  },
  {
    name: "Bangladesh",
    code: "BD",
    dialCode: "+880",
    flag: "🇧🇩",
    phoneLength: 10,
  },
  {
    name: "Belarus",
    code: "BY",
    dialCode: "+375",
    flag: "🇧🇾",
    phoneLength: 9,
  },
  {
    name: "Belgium",
    code: "BE",
    dialCode: "+32",
    flag: "🇧🇪",
    phoneLength: 9,
  },
  {
    name: "Benin",
    code: "BJ",
    dialCode: "+229",
    flag: "🇧🇯",
    phoneLength: 8,
  },
  {
    name: "Bhutan",
    code: "BT",
    dialCode: "+975",
    flag: "🇧🇹",
    phoneLength: 8,
  },
  {
    name: "Bolivia",
    code: "BO",
    dialCode: "+591",
    flag: "🇧🇴",
    phoneLength: 8,
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    dialCode: "+387",
    flag: "🇧🇦",
    phoneLength: 8,
  },
  {
    name: "Botswana",
    code: "BW",
    dialCode: "+267",
    flag: "🇧🇼",
    phoneLength: 8,
  },
  {
    name: "Brazil",
    code: "BR",
    dialCode: "+55",
    flag: "🇧🇷",
    phoneLength: 11,
  },
  {
    name: "Bulgaria",
    code: "BG",
    dialCode: "+359",
    flag: "🇧🇬",
    phoneLength: 9,
  },
  {
    name: "Burundi",
    code: "BI",
    dialCode: "+257",
    flag: "🇧🇮",
    phoneLength: 8,
  },
  {
    name: "Cambodia",
    code: "KH",
    dialCode: "+855",
    flag: "🇰🇭",
    phoneLength: 9,
  },
  {
    name: "Cameroon",
    code: "CM",
    dialCode: "+237",
    flag: "🇨🇲",
    phoneLength: 9,
  },
  {
    name: "Canada",
    code: "CA",
    dialCode: "+1",
    flag: "🇨🇦",
    phoneLength: 10,
  },
  {
    name: "Chile",
    code: "CL",
    dialCode: "+56",
    flag: "🇨🇱",
    phoneLength: 9,
  },
  {
    name: "China",
    code: "CN",
    dialCode: "+86",
    flag: "🇨🇳",
    phoneLength: 11,
  },
  {
    name: "Colombia",
    code: "CO",
    dialCode: "+57",
    flag: "🇨🇴",
    phoneLength: 10,
  },
  {
    name: "Costa Rica",
    code: "CR",
    dialCode: "+506",
    flag: "🇨🇷",
    phoneLength: 8,
  },
  {
    name: "Croatia",
    code: "HR",
    dialCode: "+385",
    flag: "🇭🇷",
    phoneLength: 9,
  },
  {
    name: "Cuba",
    code: "CU",
    dialCode: "+53",
    flag: "🇨🇺",
    phoneLength: 8,
  },
  {
    name: "Cyprus",
    code: "CY",
    dialCode: "+357",
    flag: "🇨🇾",
    phoneLength: 8,
  },
  {
    name: "Czech Republic",
    code: "CZ",
    dialCode: "+420",
    flag: "🇨🇿",
    phoneLength: 9,
  },
  {
    name: "Denmark",
    code: "DK",
    dialCode: "+45",
    flag: "🇩🇰",
    phoneLength: 8,
  },
  {
    name: "Dominican Republic",
    code: "DO",
    dialCode: "+1-809",
    flag: "🇩🇴",
    phoneLength: 10,
  },
  {
    name: "Ecuador",
    code: "EC",
    dialCode: "+593",
    flag: "🇪🇨",
    phoneLength: 9,
  },
  {
    name: "Egypt",
    code: "EG",
    dialCode: "+20",
    flag: "🇪🇬",
    phoneLength: 10,
  },
  {
    name: "El Salvador",
    code: "SV",
    dialCode: "+503",
    flag: "🇸🇻",
    phoneLength: 8,
  },
  {
    name: "Estonia",
    code: "EE",
    dialCode: "+372",
    flag: "🇪🇪",
    phoneLength: 8,
  },
  {
    name: "Ethiopia",
    code: "ET",
    dialCode: "+251",
    flag: "🇪🇹",
    phoneLength: 9,
  },
  {
    name: "Fiji",
    code: "FJ",
    dialCode: "+679",
    flag: "🇫🇯",
    phoneLength: 7,
  },
  {
    name: "Finland",
    code: "FI",
    dialCode: "+358",
    flag: "🇫🇮",
    phoneLength: 9,
  },
  {
    name: "France",
    code: "FR",
    dialCode: "+33",
    flag: "🇫🇷",
    phoneLength: 9,
  },
  {
    name: "Georgia",
    code: "GE",
    dialCode: "+995",
    flag: "🇬🇪",
    phoneLength: 9,
  },
  {
    name: "Germany",
    code: "DE",
    dialCode: "+49",
    flag: "🇩🇪",
    phoneLength: 10,
  },
  {
    name: "Ghana",
    code: "GH",
    dialCode: "+233",
    flag: "🇬🇭",
    phoneLength: 9,
  },
  {
    name: "Greece",
    code: "GR",
    dialCode: "+30",
    flag: "🇬🇷",
    phoneLength: 10,
  },
  {
    name: "Guatemala",
    code: "GT",
    dialCode: "+502",
    flag: "🇬🇹",
    phoneLength: 8,
  },
  {
    name: "Honduras",
    code: "HN",
    dialCode: "+504",
    flag: "🇭🇳",
    phoneLength: 8,
  },
  {
    name: "Hong Kong",
    code: "HK",
    dialCode: "+852",
    flag: "🇭🇰",
    phoneLength: 8,
  },
  {
    name: "Hungary",
    code: "HU",
    dialCode: "+36",
    flag: "🇭🇺",
    phoneLength: 9,
  },
  {
    name: "Iceland",
    code: "IS",
    dialCode: "+354",
    flag: "🇮🇸",
    phoneLength: 7,
  },
  {
    name: "India",
    code: "IN",
    dialCode: "+91",
    flag: "🇮🇳",
    phoneLength: 10,
  },
  {
    name: "Indonesia",
    code: "ID",
    dialCode: "+62",
    flag: "🇮🇩",
    phoneLength: 10,
  },
  {
    name: "Iran",
    code: "IR",
    dialCode: "+98",
    flag: "🇮🇷",
    phoneLength: 10,
  },
  {
    name: "Iraq",
    code: "IQ",
    dialCode: "+964",
    flag: "🇮🇶",
    phoneLength: 10,
  },
  {
    name: "Ireland",
    code: "IE",
    dialCode: "+353",
    flag: "🇮🇪",
    phoneLength: 9,
  },
  {
    name: "Israel",
    code: "IL",
    dialCode: "+972",
    flag: "🇮🇱",
    phoneLength: 9,
  },
  {
    name: "Italy",
    code: "IT",
    dialCode: "+39",
    flag: "🇮🇹",
    phoneLength: 10,
  },
  {
    name: "Jamaica",
    code: "JM",
    dialCode: "+1-876",
    flag: "🇯🇲",
    phoneLength: 10,
  },
  {
    name: "Japan",
    code: "JP",
    dialCode: "+81",
    flag: "🇯🇵",
    phoneLength: 10,
  },
  {
    name: "Jordan",
    code: "JO",
    dialCode: "+962",
    flag: "🇯🇴",
    phoneLength: 9,
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    dialCode: "+7",
    flag: "🇰🇿",
    phoneLength: 10,
  },
  {
    name: "Kenya",
    code: "KE",
    dialCode: "+254",
    flag: "🇰🇪",
    phoneLength: 9,
  },
  {
    name: "Kuwait",
    code: "KW",
    dialCode: "+965",
    flag: "🇰🇼",
    phoneLength: 8,
  },
  {
    name: "Lebanon",
    code: "LB",
    dialCode: "+961",
    flag: "🇱🇧",
    phoneLength: 8,
  },
  {
    name: "Liechtenstein",
    code: "LI",
    dialCode: "+423",
    flag: "🇱🇮",
    phoneLength: 7,
  },
  {
    name: "Lithuania",
    code: "LT",
    dialCode: "+370",
    flag: "🇱🇹",
    phoneLength: 8,
  },
  {
    name: "Luxembourg",
    code: "LU",
    dialCode: "+352",
    flag: "🇱🇺",
    phoneLength: 9,
  },
  {
    name: "Malaysia",
    code: "MY",
    dialCode: "+60",
    flag: "🇲🇾",
    phoneLength: 9,
  },
  {
    name: "Mexico",
    code: "MX",
    dialCode: "+52",
    flag: "🇲🇽",
    phoneLength: 10,
  },
  {
    name: "Morocco",
    code: "MA",
    dialCode: "+212",
    flag: "🇲🇦",
    phoneLength: 9,
  },
  {
    name: "Netherlands",
    code: "NL",
    dialCode: "+31",
    flag: "🇳🇱",
    phoneLength: 9,
  },
  {
    name: "New Zealand",
    code: "NZ",
    dialCode: "+64",
    flag: "🇳🇿",
    phoneLength: 9,
  },
  {
    name: "Nigeria",
    code: "NG",
    dialCode: "+234",
    flag: "🇳🇬",
    phoneLength: 10,
  },
  {
    name: "Norway",
    code: "NO",
    dialCode: "+47",
    flag: "🇳🇴",
    phoneLength: 8,
  },
  {
    name: "Oman",
    code: "OM",
    dialCode: "+968",
    flag: "🇴🇲",
    phoneLength: 8,
  },
  {
    name: "Pakistan",
    code: "PK",
    dialCode: "+92",
    flag: "🇵🇰",
    phoneLength: 10,
  },
  {
    name: "Palestine",
    code: "PS",
    dialCode: "+970",
    flag: "🇵🇸",
    phoneLength: 9,
  },
  {
    name: "Panama",
    code: "PA",
    dialCode: "+507",
    flag: "🇵🇦",
    phoneLength: 8,
  },
  {
    name: "Paraguay",
    code: "PY",
    dialCode: "+595",
    flag: "🇵🇾",
    phoneLength: 9,
  },
  {
    name: "Peru",
    code: "PE",
    dialCode: "+51",
    flag: "🇵🇪",
    phoneLength: 9,
  },
  {
    name: "Philippines",
    code: "PH",
    dialCode: "+63",
    flag: "🇵🇭",
    phoneLength: 10,
  },
  {
    name: "Poland",
    code: "PL",
    dialCode: "+48",
    flag: "🇵🇱",
    phoneLength: 9,
  },
  {
    name: "Portugal",
    code: "PT",
    dialCode: "+351",
    flag: "🇵🇹",
    phoneLength: 9,
  },
  {
    name: "Qatar",
    code: "QA",
    dialCode: "+974",
    flag: "🇶🇦",
    phoneLength: 8,
  },
  {
    name: "Romania",
    code: "RO",
    dialCode: "+40",
    flag: "🇷🇴",
    phoneLength: 10,
  },
  {
    name: "Russia",
    code: "RU",
    dialCode: "+7",
    flag: "🇷🇺",
    phoneLength: 10,
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    dialCode: "+966",
    flag: "🇸🇦",
    phoneLength: 9,
  },
  {
    name: "Singapore",
    code: "SG",
    dialCode: "+65",
    flag: "🇸🇬",
    phoneLength: 8,
  },
  {
    name: "Slovakia",
    code: "SK",
    dialCode: "+421",
    flag: "🇸🇰",
    phoneLength: 9,
  },
  {
    name: "South Africa",
    code: "ZA",
    dialCode: "+27",
    flag: "🇿🇦",
    phoneLength: 9,
  },
  {
    name: "South Korea",
    code: "KR",
    dialCode: "+82",
    flag: "🇰🇷",
    phoneLength: 10,
  },
  {
    name: "Spain",
    code: "ES",
    dialCode: "+34",
    flag: "🇪🇸",
    phoneLength: 9,
  },
  {
    name: "Sri Lanka",
    code: "LK",
    dialCode: "+94",
    flag: "🇱🇰",
    phoneLength: 9,
  },
  {
    name: "Sweden",
    code: "SE",
    dialCode: "+46",
    flag: "🇸🇪",
    phoneLength: 9,
  },
  {
    name: "Switzerland",
    code: "CH",
    dialCode: "+41",
    flag: "🇨🇭",
    phoneLength: 9,
  },
  {
    name: "Syria",
    code: "SY",
    dialCode: "+963",
    flag: "🇸🇾",
    phoneLength: 9,
  },
  {
    name: "Taiwan",
    code: "TW",
    dialCode: "+886",
    flag: "🇹🇼",
    phoneLength: 9,
  },
  {
    name: "Thailand",
    code: "TH",
    dialCode: "+66",
    flag: "🇹🇭",
    phoneLength: 9,
  },
  {
    name: "Tunisia",
    code: "TN",
    dialCode: "+216",
    flag: "🇹🇳",
    phoneLength: 8,
  },
  {
    name: "Turkey",
    code: "TR",
    dialCode: "+90",
    flag: "🇹🇷",
    phoneLength: 10,
  },
  {
    name: "Ukraine",
    code: "UA",
    dialCode: "+380",
    flag: "🇺🇦",
    phoneLength: 9,
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    dialCode: "+971",
    flag: "🇦🇪",
    phoneLength: 9,
  },
  {
    name: "United Kingdom",
    code: "GB",
    dialCode: "+44",
    flag: "🇬🇧",
    phoneLength: 10,
  },
  {
    name: "United States",
    code: "US",
    dialCode: "+1",
    flag: "🇺🇸",
    phoneLength: 10,
  },
  {
    name: "Uruguay",
    code: "UY",
    dialCode: "+598",
    flag: "🇺🇾",
    phoneLength: 8,
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    dialCode: "+998",
    flag: "🇺🇿",
    phoneLength: 9,
  },
  {
    name: "Venezuela",
    code: "VE",
    dialCode: "+58",
    flag: "🇻🇪",
    phoneLength: 10,
  },
  {
    name: "Vietnam",
    code: "VN",
    dialCode: "+84",
    flag: "🇻🇳",
    phoneLength: 9,
  },
  {
    name: "Yemen",
    code: "YE",
    dialCode: "+967",
    flag: "🇾🇪",
    phoneLength: 9,
  },
  {
    name: "Zambia",
    code: "ZM",
    dialCode: "+260",
    flag: "🇿🇲",
    phoneLength: 9,
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    dialCode: "+263",
    flag: "🇿🇼",
    phoneLength: 9,
  },
];

export default countryData;